# Generated by Django 5.2.15 on 2026-06-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_hostel_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.CharField(default='https://tse4.mm.bing.net/th/id/OIP.qlj7qCwszhzGTRTmYlVYXgHaHa?pid=Api&h=220&P=0', max_length=200),
        ),
    ]
