# Generated by Django 5.2.15 on 2026-06-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.CharField(default='https://cdn-icons-png.freepik.com/512/14228/14228079.png', max_length=200),
        ),
    ]
