# Generated by Django 5.2.15 on 2026-06-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_food_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='ingrediant',
            new_name='description',
        ),
    ]
