# Generated by Django 5.2.15 on 2026-06-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_rename_ingrediant_food_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hostel',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
